### ISSUE TITLE
Can't disable it

### ISSUE THREAD

**Issue by TareqElMasriDev** [Waitsnake/AnimatedGif#10]
I've tried to do as many tries as possible to disable and seems not to be able to.

**Comment by Waitsnake** [comment]
Sounds for me like you have enabled the wallpaper/background mode of the screensaver. 
Or do you mean something else?

The background mode is a wanted feature of the screensaver for people that like it. But you don't need the background mode. The screensaver can also run as a normal screensaver without it.

You can disable the background mode:
1) Open System Preferences of OSX
2) press on "Desktop & Screen Saver"
3) press on Tab "Screen Saver"
4) select "AnimatedGif" on the left
5) press on "Screen Saver Options ..." on the right, this opens the option window of screensaver
6) look at line "Run screensaver in background (launch agent):" here the button "load" should be blue if the background mode is active
7) press on button "unload" to stop the background mode
8) press on button "OK"

Please give a comment if this solves your problem. 
Otherwise please explain a bit more in detail what happens at your computer.

**Comment by TareqElMasriDev** [comment]
Tried that a lot and doesn't work.

**Comment by Waitsnake** [comment]
Maybe you changed some file access properties in your user account and the screensaver can't remove the launch agent file that starts the background mode?

Try to delate it manually:
1) Open the Terminal-App of OSX it should be open in your user folder (check it with "pwd" should show "/User/your_user_name")
2) "rm Library/LaunchAgents/com.stino.animatedgif.plist"
3) "killall ScreenSaverEngine"

If step 2) did not work some file access properties are wrong.
Try than: "sudo rm Library/LaunchAgents/com.stino.animatedgif.plist" and enter your admin password.

Edit:
Step 3) alone seems not enough because it is already registered in the launchd.
So at step 3) you need to "Log Out" your user and "Log In" again or make a reboot of OSX.

Edit 2:
Seems I forgot a bit over the time. The cleanest way to stop it was:
1) Open the Terminal-App of OSX it should be open in your user folder (check it with "pwd" should show "/User/your_user_name")
2) "launchctl unload Library/LaunchAgents/com.stino.animatedgif.plist"
3) "rm Library/LaunchAgents/com.stino.animatedgif.plist"

Can you please tell me the version of your MacOSX? 
I use El Capitan 10.11.6.

Maybe you already use the newest macOS 10.12 ?

**Comment by Waitsnake** [comment]
Hi TareqElMasri,
could you stop the program as I described it in my last post under "Edit 2"?
And which version of MacOS do you run?

**Comment by Waitsnake** [comment]
Closed because problem/behavior is not reproducible.
