### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by EvilMilkshake** [Waitsnake/AnimatedGif#11]
Any chance of making the gif random from a folder? Allow for a change every X amount of minutes?

**Comment by Waitsnake** [comment]
Sorry if I let you hang with an answer. Actually I liked your idea with the slideshow too. Thats why I let the issue open and put an 'enhancement' label on it.

Unfortunately this enhancement needs a bit more to do than all other issues here before, because the structure of the code is not prepared for this feature. Especially the old feature that loads a GIF completely into memory at the start of the saver to save cpu time during the animation is in conflict with this new feature, since the loading into memory needs quite some time(a few seconds if you have really large GIF). So between the changes of two pictures there would be an annoying long time if you enable the load into memory option.

I also need to learn more a about using timer in Objective-C first. And I'm wondering if there is a easy way to start and stop the saver programmatically during the timer procedure and than just change the picture to load randomly? Because this could help to implement the feature with less restructuring of the code.

So you see I still chew over how to integrate this feature...

**Comment by Waitsnake** [comment]
Ok I implement the feature you have requested.
Please have a look at the new Release 1.2 and give it a try.
