### ISSUE TITLE
Directory Mode is Greyed Out 

### ISSUE THREAD

**Issue by shamesung** [Waitsnake/AnimatedGif#18]
Directory Mode is Greyed Out so selecting a directory also doesn't work only single file is allowed
![screen shot 2017-07-08 at 9 58 23 pm](https://user-images.githubusercontent.com/6269751/27990820-963fca44-6428-11e7-92b9-e31360bb1036.png)

**Comment by Waitsnake** [comment]
This is actually not a bug of AnimatedGif, but maybe a GUI design flaw of me(?). The "single file mode" and "directory mode" in the GUI is only a reminder if you last time select a directory or an file. I made this because in "single file mode" you can not change the random timer. And in "directory mode" the value from gif file is not shown, because in this mode the file always randomly changes and it brings no value to know what fps the random GIF in the preview mode has. So this GUI element is **always** grayed out. I could remove this passive GUI element since it obviously confuses you more as it helps?


But I think your real problem is that you don't know how the standard file dialog in MacOS works? I could not blame you for this since I also would call it an inconvenience compared to how the file dialog of linux or windows works. But I can't change the file dialog since it is part of the operating system.

The inconvenience is that any standard file dialog in the MacOS of any application always starts in a kind of collapsed view. In the collapsed view you can only see the content of the highest selected directory level. 

To have an expanded view of the file dialog that shows different directory levels at once you need to click on the directory name that is on top of the file dialog window and select a different directory level in the drop down list. After this the whole dialog is in the expanded view and shows different directory levels at once. Now just click on an folder that contains some GIF's an press Open.

Unfortunately the API gives no option to open the file dialog already in the expanded view as far as I know.

**Comment by Waitsnake** [comment]
I think the new GUI element for file / directory mode was too confusing and so I removed it.
For the confusing way the how the OSX file dialog works (as I explained it above) I try to find a workaround that hopefully makes the use of it more intuitive. 
When now opening the file dialog not the last selected file/directory is open, but one(in case of directory) or two(in case of file) path levels above the last selected file/directory.
Now the user can see more of the path structure and has no need to press the "directory name that is on top of the file dialog window" first to reach the same goal.

Hope the works out better as before. The fix comes with commit 56.
