### ISSUE TITLE
GIF loads too slow

### ISSUE THREAD

**Issue by shamesung** [Waitsnake/AnimatedGif#2]
GIF will look okay when viewed in sys pref. But when previewed or seen as screensaver the gif runs slow
Tried running at 30 fps with manual override setting.
[Issue.mov.zip](https://github.com/Stino/AnimatedGif/files/101665/Issue.mov.zip)

**Comment by shamesung** [comment]
![circle-loop-v2](https://cloud.githubusercontent.com/assets/6269751/12527596/cfed07fe-c143-11e5-8fbe-77e144bd288c.gif)

**Comment by shamesung** [comment]
Thats the GIF file

**Comment by Waitsnake** [comment]
Actually I saw in your video that in the small preview window your test gif runs  at normal speed, but when you start the full screen preview mode it runs slower.

I try your test gif image at my Macbook Air (late 2010) with OSX 10.9 Mavericks on it. On my system I could not reproduce your issue. In both cases the image runs at normal speed.

At the moment I can say just this, that in the small preview window and in the full screen window the gif is shown with different draw functions.
The fullscreen window uses Core Image function "drawInRect:fromRect:operation:fraction:", because I hoped this could accelerate the draw speed (Manual say that CoreImage uses Hardware Acceleration). The small preview window uses function "drawInRect:" from NSImage just because in preview mode the CoreImage was not working correct.

So I have different assumptions what could maybe cause the different behavior on your system.
1.) Your system had a lot of background tasks running when making the video. Next time check this with the activity monitor. Function „drawInRect:fromRect:operation:fraction“ still needs a lot of cpu power and if this was missing this could maybe lead to the slow running. Your gif has inside 25 fps and you even run it manual with 30 fps. This could be a reason.

2.) I see at the aqua optic you have a different operating system version (10.10 or 10.11 ?). Probably drawInRect:fromRect:operation:fraction is on newer operating systems even less performant as in 10.9 ?

3.) You have an different hardware and maybe running at a hackintosh system without any good GPU hardware acceleration? Yah, I know this is a strange guess, but how knows what people doing out there in this large world? ;-)

Even on my system I’m not that happy with performance of the gif animation in general, thats why I add the manual change of fps to have the possibility to choose a lower fps that needs less process power. Your test gif at 25 fps in full screen stretched mode cost on my system 59-62% of CPU power from my 200%(2 Cores). I profile the code with „Instruments“ and I can see that 91,5% of the CPU time of the screensaver is used by API call drawInRect:fromRect:operation:fraction itself. So I try out different API draw functions from CoreImage, CoreGraphics, CoreAnimation and NSImage, but I could not better the performance with the other ones. If someone has an idea how to better the draw performance than don’t hesitate to tell me. Pull requests are welcome. :)

**Comment by shamesung** [comment]
I'm running 10.11.4 Beta :P on Macbook Air 2014
I have made the screensaver in quartz composer it runs at full speed on my mac.
It maybe of help you.
[AnimatedGIF.zip](https://github.com/Stino/AnimatedGif/files/111535/AnimatedGIF.zip)

**Comment by Waitsnake** [comment]
At least at my old MBA the Quartz Composer script runs even more slowly as the screensaver does and needs 89-92% of CPU power when running it with your GIF?

This leads me to the thought that the graphics drivers for my MBA 2010 (has Nvidia GPU 320M and was made for 10.6) not work that great together with the newer OSX versions like 10.9(and newer) and that's maybe the reason I see no benefit when using the so called "accelerated" API functions on my system. Final conclusion is that my MBA is really too old and I absolutely need a new Mac! :-O

**Comment by Waitsnake** [comment]
I change the hole render routine to use now OpenGL instead of CoreImage. At least my system this step alone saves a lot of CPU power.

This alone drops the CPU use with your test gif on my system from 59-62% down to 26-28% (2 Cores = max 200%).

I also an new option was added to load hole animation at start time into memory. This makes the start of cause much slower(especially your test gif because it has 168 frames(!) ), but during animation it saves even more CPU time. CPU use with your test gif drops than down on my system to 13-15%.

Without the loading your test gif completely into memory ScreenSaverEngine needs 41 MB of RAM. But when loading your test gif completely into memory ScreenSaverEngine needs 350 MB of RAM. 

Because of this I finally found out, what was the strange thing with your test gif. Your gif has 168 frames(animation steps) by a size of 800x600. Most gif's I use before have only 30 or less frames. Using one of those gif's ScreenSaverEngine uses only around 50 MB of RAM when loading complete into memory.

Anyway try the new version out and give me some feedback. Hope the problem is solved now.

**Comment by shamesung** [comment]
Thank so much! It's working! :dancers:
CPU usage hasn't increased on my end so thats a good sign.
[Untitled.mov.zip](https://github.com/Stino/AnimatedGif/files/120652/Untitled.mov.zip)

**Comment by Waitsnake** [comment]
I'm glad to hear it is running on your system now. 😎
Thanks for the challenge, I learned a lot of new things thereby.
By the way at friday I finally order a new Mac. An MBA 2015 that probably will come with an 10.11. 
But it still needs some days until it is shipped...
