### ISSUE TITLE
five stars

### ISSUE THREAD

**Issue by Olivered** [Waitsnake/AnimatedGif#24]
I love your animatedgif screensaver. great code, it does the job.
I like to use it with http://stormandsky.com/gifs.html
But I also use
http://s.sudre.free.fr/Software/SaveHollywood/about.html 
https://pastebin.com/q8Y373zK 
https://flixel.com/cinemagraphs/nature/ 

personally, I do use SaveHollywood with cinemagraphs from flixel, 
and a custom launch agent. I have more mp4s, they use less memory,
2% cpu vs 5% for a gif. BUT!
it doesn't truly seamlessly loop. gifs loop a little bit better.
It is harder to tell where they transition, sometimes even impossible because
they will rewind for truly seamless loop.

**Comment by Waitsnake** [comment]
Hi Olivered,
good to hear you like the project! Github has a star function if you really mean it. ;-)

I take a short look at the stormy gifs and they are really nice. I personally use at the moment the GIF's from 1041uuu as screensaver. They are a fantastic pice of art too.
http://1041uuu.tumblr.com

SaveHollywood is another kind of project since it plays video files (mov, mp4, m4v). But it don't support GIF's like AnimatedGif does. If you play H.264 or H.265 videos you can use the build in libraries of the Mac operating system witch are even accelerated completely in hardware by the graphics chip. And so it is no wonder if they have only 2% CPU. Sorry there is no way to beet this with GIF's as long as there is no better support in hardware and in software for this format. 

Well I try to save CPU time in the past as good as I can and use OpenGL for acceleration. And I compared AnimatedGif with a few other solutions for playing GIF's as screensaver in OSX that I could found on the web. Most of them use 30-40% CPU or even more. So the 5% of AnimatedGif already is a good value. I think you already use the option "Load animation at start into memory (saves CPU time)" or don't you?

But if the videos did the job for you than go for it. Maybe there are tools out there that can convert the stormy GIF's into an mp4 video.

**Comment by Waitsnake** [comment]
Closed since this was more a comment than a bug report.

**Comment by Olivered** [comment]
I have figured out how to get the screensaver to load and remain loaded regardless of whether Reboot, resume from sleep, lock/unlock screen, etc.
But it required tampering with OSX.
I ran sudo cp  /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine /usr/bin/background
then modified my plist from the pastebin to point to that binary.
then I installed sleepwatcher "brew install sleepwatcher"
then I put 
"
#!/bin/bash
launchctl unload  ~/Library/LaunchAgents/local.job.screensaver.plist
launchctl load  ~/Library/LaunchAgents/local.job.screensaver.plist"
into ~/.wakeup

Now the background, no matter what screensaver you use, loads when your screen locks, unlocks,
etc etc.

**Comment by Waitsnake** [comment]
Interesting.
But for these kind of tampering you need to disable the System Integrity Protection since folder /usr is part of the protection (can be disabled by running "csrutil disable" in recovery mode). Or do you run an pre-El-Capitan system?
