### ISSUE TITLE
GIF is zoomed in even if stretch to screen option is disabled

### ISSUE THREAD

**Issue by shamesung** [Waitsnake/AnimatedGif#3]

**Comment by Waitsnake** [comment]
This is actually no real issue. The view options worked as I intended them to work. ;-)
I wanted two view options, one to stretch image maximal to screen and one option to stretch image but keep the image ratio as it is. In second case you will most likely see an border and therefore I added also the background color option that the borders can a bit customized. But you are right with one thing, the text I choose for this option was more or less wrong.

Since you like an third option to keep image original size I replaced the old checkbox with an popup box with three options. 
The view options are: 
- strech with keep image ratio
- strech maximal to screen
- keep image original size

**Comment by shamesung** [comment]
excellent
