### ISSUE TITLE
Having trouble running in the background

### ISSUE THREAD

**Issue by ghost** [Waitsnake/AnimatedGif#34]
I'm just installing AnimatedGif, and for some reason it doesn't work in my background mode. I'm not sure if it has to do with macOS High Sierra or if even a version of Xcode I'm using (8.2.1).
I'm following the instructions on the installer and I tried looking through all of the questions before asking. If anyone can help troubleshoot, that'd be awesome.

**Comment by Waitsnake** [comment]
On wich exact version of OSX are you? I mean even High Sierra has different minor versions from 10.13.0 till 10.13.5. 
The thing is that Apple had a lot of issues with the ScreenSaverEngine in High Sierra and there are ongoing rumors that Apple still changes things between minor versions at the ScreenSaverEngine. Maybe you run into some new problem here? I for myself stopped that nonsense of having installed always the newest major version of macOS every year and playing Beta-Tester for them and so I'm still on El Capitan since this is now rocksolid and still official supported by Apple. Because I'm on El Capitan High Sierra is not official supported by AnimatedGif. But I had some feedback of people using AnimatedGif on High Sierra where the background mode was working at least on the main screen. See for example issue #33.

What is exactly the behavior you see with AnimatedGif and background mode and what release version of AnimatedGif do you use when having this problems?

Why do you mention Xcode 8.2.1 ? Does this mean you not using the provided prebuild binaries and compile the ScreenSaver on your own?

Well the source code of AnimatedGif is until now only written and tested for Xcode 7.3.1 with SDK for OSX 10.11 El Capitan.

Anyway you can try the pre-release of AnimatedGif 1.3.7 that I add to my last comment of issue #33 if you want. [direct link to AnimatedGif 1.3.7](https://github.com/Waitsnake/AnimatedGif/files/1887828/AnimatedGif.saver.zip)

And on this side you can find all official releases and binaries of AnimatedGif from 1.0 till 1.3.6 . https://github.com/Waitsnake/AnimatedGif/releases

**Comment by Waitsnake** [comment]
Closed because submitter not helped to reproduce the problem.

Since report of issue #35 it looks like AnimatedGif is not working with 10.13.4 at all. Not even in the normal screensaver view seems to work. One issue is enough to cover that the screensaver don't work with High Sierra.
