### ISSUE TITLE
[10.13.4] black screen in normal screensaver mode

### ISSUE THREAD

**Issue by jnoxon** [Waitsnake/AnimatedGif#35]
The preview I see in Settings.app looks fine, but when I activate the screensaver, the screen is black.

I've tried 1.3.6 and the 1.3.7-beta. Running 10.13.4, two external displays on a MacBook Pro in clamshell mode.

**Comment by Waitsnake** [comment]
Well it seams Apple changes again something under the hud with new OS update 10.13.4.

Since I have no system with High Sierra and still use El Capitan I can't analyze it deeper at the moment. Sorry. But I will update the readme that High Sierra AnimatedGif no longer works in High Sierra. Maybe it will work again when Apple bring out 10.13.5. Or not witch is moreprobable, we will see.

**Comment by Waitsnake** [comment]
Thanks for reporting. I will let the report open as enhancement until Apple fixes its ScreenSaverEngine or until I migrate one day to High Sierra and find yet another workaround for what ever the problem is now. The readme is updated.

**Comment by Waitsnake** [comment]
I found this report for a similar problem for an other screensaver.
[10.13.4 Macbook Pro 13' display error](https://github.com/JohnCoates/Aerial/issues/452)

Looks this similar to your problem? Helps the Workaround they describe (turning on the screensaver clock in settings) to fix the problem? You have to know that AnimatedGif needs to automatic disable the clock when using background mode(because of issue #30). But the clock should work when background mode is disabled and using only foreground mode.

**Comment by jnoxon** [comment]
"Show with clock" was not enabled. I tried both foreground and background mode. It's certainly possible there's some other PEBKAC.

I just tried enabling the clock and using foreground mode... I see a clock and nothing else.

**Comment by Waitsnake** [comment]
I installed High Sierra to test the problem. With 10.13.4 Apple changes the behavior of the two API functions orderOut() and orderBack() to hide and unhide a window. In older versions these functions work in normal desktop mode as well as in a normal screensaver mode. But with 10.13.4 they no longer work with normal screensaver mode and leaf the screen black. As fix I don't use them for normal screensaver mode any longer. Fix comes with official 1.3.7 release (not those beta verion in the other issue report).
