### ISSUE TITLE
Cycling through the folder

### ISSUE THREAD

**Issue by TheBestJohn** [Waitsnake/AnimatedGif#45]
It would be nice, if you have multiple gifs, if you could set a cycle count to how many cycles each gif goes through before loading up another random gif from the file or have the ability to change the time between cycling.

Also on multi monitor support, if there are enough gifs in the folder, have the ability to disable duplicates so no 2 screens show the same gif

Thanks for your work this thing is great! :)

**Comment by Waitsnake** [comment]
Actually you already can select a folder instead of a single GIF file. 
Look here at this example picture. I hope it explains it better. 
![Example 1](https://raw.githubusercontent.com/Waitsnake/AnimatedGif/master/readme_extra/select_folder_example.png)

If you select a folder with GIFs the screensaver only search for GIFs directly in this folder. The screensaver do not search recursive in any sub-folders of this folder for GIFs.

There is also an option available "to change the time between cycling". This option is grayed out when you select a single GIF, but after you select a folder it is black and useable.
![Example 2](https://raw.githubusercontent.com/Waitsnake/AnimatedGif/master/readme_extra/select_a_change_time_for_folder.png)

There is also a multi monitor support implemented and on each monitor a random GIF is shown. The chance for each monitor is independent from the other (in fact each monitor gets its own process and the processes not talk among each other). Since it is random it is possible that two monitors shows the same GIF but if you have enough GIFs in the selected folder it is at least unlikely.
