### ISSUE TITLE
[MacOS 10.14] Doesn't seem to work on Mojave. 

### ISSUE THREAD

**Issue by jichardrones** [Waitsnake/AnimatedGif#55]
Display reads I am unable to use AnimatedGif with this version of Mac OS. Please contact vendor. 

Any solution? 

Thanks

**Comment by Waitsnake** [comment]
What is the exact version number of your operating system?
(Mojave is not equal Mojave since especial early versions of this operating system had a lot of issues with screensvers.)

What version of AnimatedGif do you use?

What kind of Mac Hardware do you use (model name, build year and what GPU is build in)?

Can you make an screenshot of the message you see and post it here?

**Comment by Waitsnake** [comment]
Two days ago I was still on Mojave 10.14.4 and the AnimatedGif version 1.5.2 on my system. When I saw yesterday that there was a new version of Mojave I thought that maybe the new version could cause the trouble you told from. But nope, also with Mojave 10.14.5 the screensaver 1.5.2 runs fine.

I did some research and found something that sounds similar to problem you maybe could have seen. I found an old entry in a blog from 2016 and some old issues on Github for the Aerial screensaver from 2018.

The blog entry:
http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html

The issues from Arial screensaver:
https://github.com/JohnCoates/Aerial/issues/464
https://github.com/JohnCoates/Aerial/issues/466
https://github.com/JohnCoates/Aerial/issues/478

According to the description of Aerial screensaver the problem only occurred on early developer Beta versions of Mojave. But with the stable versions of Mojave the problem was gone. The blog entry otherwise was from 2016 and that was Sierra times. Back then this problem was only related screensavers using Swift, like Arial. But AnimatedGif is implemented in Objective-C and not uses any Swift and so this seams a bit strange that this problem could occur with it.

Anyway as long as I can't reproduce your problem I can't help you any further. So take a look to the questions of my last post and try to answer them.

Any more informations?

Thanks

**Comment by konecnyna** [comment]
Working on Mojave for me!

**Comment by Waitsnake** [comment]
Closed because submitter not helped to reproduce the problem.

**Comment by RandyStevens** [comment]
I am currently having an issue with Mojave. Its an early developer release.

OXS Version: (macOS 10.15 (19A471t))
GPU: Intel Iris Graphics 6100
Model: MacBookPro12,1
Year: MacBook Pro (Retina, 13-inch, Early 2015)

The exact behavior is as follows: 
- I download the most recent release from github
- Unzip animated.saver
- Double click to install (Here i get the warning like you mention in the readme)
- Go to security/preferences
- Click the allow action like you mention in the readme
- After clicking allow anyways, it brings me back to the screensaver menu with the same unidentified developer warning. I can repeat this process ad infinitum.

**Comment by Waitsnake** [comment]
@RandyStevens  I moved your report into a new issue #57 . According to the build number **19A471t** you mentioned together with "early developer release" it seams much more likely to me you have this issue with macOS 10.15 Beta 1 (19A471t) - **Catalina** and not on macOS 10.14.5 (18F132) - **Mojave**.
