### ISSUE TITLE
More ChangeInterval options?

### ISSUE THREAD

**Issue by konecnyna** [Waitsnake/AnimatedGif#56]
Right now it seems the [change interval](https://github.com/Waitsnake/AnimatedGif/blob/14cdf6620297849d0359106c7c21c95dfa0af6aa/AnimatedGif/AnimatedGifView.m#L348) is only between 1-29minutes or never.

Would it be possible to get more options? Maybe a drop down menu of:
* 1 minute
* 30 minutes
* 1 Hour
* 6 Hours
* 1 Day

or Something? I would really love once a day opinion.

**Comment by Waitsnake** [comment]
I will think about it. Maybe the actual slider element for the time needs too replaced by a dropdown list to define such different time intervals.

**Comment by konecnyna** [comment]
Awesome, I'll see if I can help out with a PR over the weekend but i'm an Android dev 😬 so my objective c isn't great... haha

**Comment by Waitsnake** [comment]
Have a look at the new Release 1.5.3 and please do some tests. 

Actually I have only tested the seconds and minutes options by myself since hours or a day are way too much time for me. But since the timers are mapped central to the interval options in the new function getIntervalFromOption() I hope it will do.

**Comment by konecnyna** [comment]
@Waitsnake you're amazing! I'm testing currently :)

**Comment by Waitsnake** [comment]
@konecnyna do you got a chance to test it a bit ?

**Comment by konecnyna** [comment]
I've been using it since you released and it has been working great! I haven't actually time the intervals but they seem to be working as intended. 

I did notice a strange issue of the screen saver window popping out when i disconnect an external monitor or restart computer but that is prob unrelated to this change.

Feel free to close and thanks! You're awesome 😁

**Comment by Waitsnake** [comment]
Sorry I did not use it too often with multiple monitors by myself.

The main problem is the way I use the screensaver engine from Apple to run the screensaver as wallpaper. The engine had 4 modes preview (within the system preferences), normal (in foreground and on all monitors), background (in background and on all monitors) and window (within one small window for developer). Since the background mode was not working at all with Mojave (was in foreground and even blocked any access to get back to OS GUI) I replaced it when used as wallpaper with the window mode and change the window properties afterwards to bring them to background.

Since window mode is only one window I had to detect how many screens are there and than start multiple instances of screensaver engine for each monitor and I have to kill an instance when you remove an monitor. It seems the OS first move the window of an instance to an still existing monitor and this will lead to the "popping out" and later the OS send an notification that a monitor is missing and just than I kill this instance.

It maybe looks ugly but this was the price to still have a background mode for multiple monitors with Mojave. It is just a chain of workarounds around issues of macOS.

Anyway, I will close this issue now. :-)
