### ISSUE TITLE
Running Mac OS Catalina: Select file or directory button not working

### ISSUE THREAD

**Issue by irishgerman** [Waitsnake/AnimatedGif#61]
I really like this program, and it was a shame when I couldn't select the gifs I wanted to use, I would click the button and it would light up and do nothing. Hopefully, this issue is fixed!

**Comment by Waitsnake** [comment]
Me too. It was a shame when I saw that Apple had restricted the classical Screensaver API with Catalina as they put the screensaver process that runs the Screensavers into a restricted sandbox that limits the things an Screensaver is allowed to do. A Screensaver is no longer allowed to read local files or even let the user select the files he want use. This behaviour can only changed by Apple.

Maybe Apple did this for security reasons? But ironically a Screensaver is still allowed to load GIFs from a web address witch seems more dangerous to me than reading a local file. Therefore one chap on Github had made a fork of this project that allows the user to add a web address to a GIF instead of a local file. If this fork fits your needs it can be found here:
https://github.com/arneson/gif-screensaver

As for my part, I prefer to wait for Apple to fix the Screensaver API, as I prefer to load my GIFs from the local directories rather than from the web.

Apple itself already uses a new API (appex files) for its own screensavers in Catalina, which do not have these limitations, but this API is not publicly available. And so I play the waiting game until they fixed their mess. But since it hasn't been repaired in the last 4 months, I guess it will only be with the successor of Catalina.

I will close this issue here sooner or later since this is already the fourth issue we have for the same problem, see #57 , #59 and #60 .
