### ISSUE TITLE
Problem with not being able to get screen saver off of my screen.

### ISSUE THREAD

**Issue by anthron01** [Waitsnake/AnimatedGif#62]
Me and my friend downloaded this thinking it would be cool to have gifs as our background but now we both have a random screensaver stuck on our computers screens and we can't get it off.  Whenever we try to exit out of it it just reappears again over and over.  How are we supposed to remove this and just have a regular background screen.. I am sick of this screensaver being stuck there all of the time, due to this download.

**Comment by Waitsnake** [comment]
This happens when you enable the "background mode" and then remove the screensaver manually. To avoid this you need to disable the "background mode" first before removing it. Sorry there was no other way to get this feature working. I will think about implementing a warning message when someone enable the background mode.

To stop the problem quick run these two command in a terminal window:
_launchctl unload ~/Library/LaunchAgents/com.waitsnake.animatedgif.plist
rm ~/Library/LaunchAgents/com.waitsnake.animatedgif.plist_

Or download and run one of the uninstaller that are described on the project start page in section "Uninstall AnimatedGif". Here is the link to the uninstaller: https://github.com/Waitsnake/AnimatedGif/raw/master/tools/Uninstall_AnimatedGif.app.zip
