### ISSUE TITLE
Animated Gif player doesn't work on MacOS Big Sur?

### ISSUE THREAD

**Issue by StormBringer228** [Waitsnake/AnimatedGif#63]
I can't play any gifs after updating to MacOS Big Sur. Is this still an issue with the sand bagging? I am able to select and save the gif but when i exit the preferences menu and go back in it shows that it can't see the file.
![AnimatedGifHelp](https://user-images.githubusercontent.com/74646274/99498815-3a085f00-29a2-11eb-810d-cbd90f5e90b7.gif)

**Comment by Waitsnake** [comment]
Yes, as far as I know Apple still has not fixed the screensaver API with Big Sur. It is still as brocken and sandboxed as it was in Catalina.

**Comment by Waitsnake** [comment]
Here some links to Apple Developer Discussions where an Apple employee ("Eskimo") gives some hints that the old plug-in model (.saver) for screensavers is obsolete and Apple is working on a modern plug-in model, which are called "app extensions" (.appex).
https://developer.apple.com/forums/thread/127996
https://developer.apple.com/forums/thread/89482

Unfortunately even in the new XCode 12 there is still no app extension dedicated to screensavers available as it was discussed here:
https://developer.apple.com/forums/thread/649291

So sorry, but until Apple has not finished this job a normal developer can do nothing at the moment to create new decent screensaver for Catalina and Big Sur that can access some files outside the sandbox.

And even when this new app extension for screensavers will come around it is very probably it will require a complete rewrite of AnimatedGif from Objective-C to Swift first, if I interpret some of Eskimos comments correctly.

**Comment by HELPMEPLEASE0011** [comment]
wallpaper mode not work for MacOS Big Sur?

**Comment by HELPMEPLEASE0011** [comment]
![image](https://user-images.githubusercontent.com/83633983/117080743-cc01f980-ad81-11eb-9f36-fb69ff4c401f.png)

**Comment by Waitsnake** [comment]
No it is neither working in Catalina nor Big Sur. It is just one of those side effects of total sandboxing the screensaver in those macOS versions.

**Comment by nouchata** [comment]
hi, actually i'm on big sur and it's working well for me, idk why i tried to install it for a friend though i had the same error as described in this thread, any idea of why ?
![ezgif-1-b929bef26b36](https://user-images.githubusercontent.com/58337627/124152682-080cbe80-da94-11eb-8dbc-5b7622f2bd11.gif)

**Comment by Waitsnake** [comment]
The best advice I can give you is uninstall AnimatedGif completely with one of the uninstaller methods mentioned in the README.md .

**Comment by Waitsnake** [comment]
I recently checked it on Big Sur(11.5.2) myself. At first of cause you need to allow AnimatedGif to run with new dialogs from macOS. 

After granting AnimatedGif rights to run the open file dialog to select files and read those selected files is working again! Seems Apple Engineers have slightly changed the Sandbox properties for Screensaver to allow this. With this more openness AnimatedGif can now at least run as normal screensaver again and allow the user to select its own gifs on his own disk.

But AnimatedGif has still issues under Big Sur:

1) Using the background mode is no longer working as HELPMEPLEASE0011 pointed out. AnimatedGif used to start background mode by creating an LaunchAgent plist in user folder, but this part is still sandboxed and I when started you can see this log-entry in system.log .
_Sandbox: legacyScreenSave(12345) deny(1) file-write-create /Users/username/Library/LaunchAgents/com.waitsnake.animatedgif.plist_

2) when I created this LaunchAgent file manually and start it the screensaver runs in a norma foreground window and not as a background window as intended. This can be also a Sandbox effect since AnimatedGif changed the window properties of ScreenSaverEngine for this wich is presumably not longer allowed.

3) At least on my new Big Sur machine (maybe because of different graphic driver ?) the drawing of the text "Please select a file or folder." when no pictures is selected looks tattered. I need to analyse why this is.

4) There are smaller new warnings when importing the project into Xcode 12.5.1 that can be fixed easily. 

Conclusion:
1) and 2. make the whole background feature not possible under Big Sur and I think about just disabling this feature completely then Big Sur is detected (e.g. make buttons in property window invisible).

3. I need to debug this deeper and to see if I can find a fix or workaround for this. I used the drawAtPoint function to render the text into a texture that texture is just rendered on screen by Metal or OpenGL. I saw this tattered text output on both Metal and OpenGL. While rendering of normal images(gifs) as texture is still working fine.

4. I already fixed all warning locally on my machine and can compile screensaver to run it natively on Intel and M1 machines. Therefore also OSX 10.9 (Mavericks) support needs to be dropped. But since minimum running is still OSX 10.10 (Yosemite) then I thing most people could live with this if we add native M1 support instead.

**Comment by Waitsnake** [comment]
I fixed 4. with commit [Import to Xcode 12.5.1](https://github.com/Waitsnake/AnimatedGif/commit/34b5ab677114081902021faad901e38f733f0d3f).

I add a workaround for 1. and 2. with [Disable background mode for newer OSs](https://github.com/Waitsnake/AnimatedGif/commit/960207723f5b4deca5d129d04b50f8564adedf82).

I fixed 3. with commit [fix text draw functions](https://github.com/Waitsnake/AnimatedGif/commit/472fd88252d2409249263393d147f6b188c03457).
