### ISSUE TITLE
gif not found

### ISSUE THREAD

**Issue by zryuek** [Waitsnake/AnimatedGif#65]
I was able to select the file and see it show up on the screensaver menu, but when i actually go into the screensaver, it says i didnt choose any file.

**Comment by Waitsnake** [comment]
First answer some questions please since you are not giving many details to properly classify the problem.

If I would just write for example "I was able to select the file and see it show up on the screensaver menu and when i actually go into the screensaver, I could see my Gif." than this would be also true but it would also not help you very much.

What version of AnimatedGif are you using?
What exact macOS version are you using? 
On what hardware you are using it (e.g. MBA 2020 M1 or MBP 2016 Intel)?

To my knowledge AnimatedGif was not working with Catalina at all, because of too hard sandboxing of Screensavers in general by Apple so that a user was not even allowed to select its own files. And what you describe sound pretty much like this and that is why I ask you the above questions. See issue #57 for more details.

But also most versions of Bis Sur version had the exact same issue with too hard sandboxing as Catalina. Just recently with version 11.5.2 on an MBA 2020 M1 I saw it working again. See issue #63 for more details.

**Comment by zryuek** [comment]
macOS version: 10.15.7
release: 1.5.4

2.3GHz quad-core Intel Core i7

**Comment by Waitsnake** [comment]
Thanks for answering. Then it is confirmed that AnimatedGif is still not working with Catalina.
But since I can break the security mechanisms of macOS I can do nothing about it if Apple has closed this system too much (in this case the broken ScreenSaver API of Catalina). :-(

**Comment by zryuek** [comment]
oh wait yeah it WAS big sur but it went back to catatlina after reinstalling the harddrive

**Comment by kavlih** [comment]
i also have this issue but with big sur (11.6) and the release 1.5.4
