### ISSUE TITLE
Unable to run in background mode

### ISSUE THREAD

**Issue by Lith1um** [Waitsnake/AnimatedGif#68]
I'm having trouble running this in background mode, the option is disabled for me.

I'm running on Monterey 12.3, unsure if the button being disabled is related to the OS version or not.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/15013204/181746211-ea8e792c-1705-4b0b-ab59-9aead17bf5ad.png">

**Comment by Waitsnake** [comment]
If you run AnimatedGif on macOS Catalina, Big Sur, Monterey, Ventura or higher version of macOS, this behaviour is intended.

Due to Apple sandboxed the hole Screensaver Engine starting with macOS Catalina without giving the programmer of a screensaver the possibility to ask the user for more permissions (like a normal Application can do) this feature is no longer possible (see analysis in this old [issue](https://github.com/Waitsnake/AnimatedGif/issues/63#issuecomment-898346138)). If a macOS version higher as macOS Mojave is detected the button is disabled. The change was done with this [commit](https://github.com/Waitsnake/AnimatedGif/commit/960207723f5b4deca5d129d04b50f8564adedf82).

But you can still use this feature on older versions of macOS like Mavericks, Yosemite, El Capitan, Sierra, High Sierra and Mojave. On this macOS versions the button will be enabled.
