### ISSUE TITLE
Not really an issue - Aesthetics

### ISSUE THREAD

**Issue by shamesung** [Waitsnake/AnimatedGif#7]
Can you put preview images into your release?
Goes into 
AnimatedGif.saver/Contents/Resources/en.lproj/
AnimatedGif.saver/Contents/Resources/es.lproj/
AnimatedGif.saver/Contents/Resources/de.lproj/

NAME: thumbnail.png

NAME: thumbnail@2x.png

Note: Images removed.

**Comment by Waitsnake** [comment]
Actually I liked the idea of an thumbnail and even your suggestion looks really nice, but I make an google reverse image search for this picture and it don't looked like your are the author of this picture and so I can't publish it here at GitHub, sorry. Since you know the trick how to replace it you can use any thumbnail you like on your Mac and nobody will care.

Anyway I tried to create an thumbnail completely by myself with Pixelmator and add this one to the project. Maybe you like this too.
![thumbnail 2x](https://cloud.githubusercontent.com/assets/942085/13543062/133e7b60-e268-11e5-8efb-df243d6ad663.png)
![thumbnail](https://cloud.githubusercontent.com/assets/942085/13543083/3b870088-e268-11e5-83b7-69766f4e747f.png)

After compiling the two pictures "thumbnail.png" and "thumbnail@2x.png" are replaced by Xcode 6.2 and only one "thumbnail.tiff" remains in the Resources folder. This one tiff contains two images, a low resolution (58x90px) and a high resolution (116x180px) version.

**Comment by shamesung** [comment]
Awesome, thanks buddy.
