### ISSUE TITLE
Excessive CPU usage while connected to an external display

### ISSUE THREAD

**Issue by shamesung** [Waitsnake/AnimatedGif#8]
Title says it all, there's excessive CPU usage while connected to an external display
Fans start running at full speed when the screensaver comes on. When there is no external display connected, it is fine.

**Comment by Waitsnake** [comment]
Hi Shame Sung,
I did a couple of tests with the systems I have here.
- new 27" 4K Display from LG
- old 22" Display from Samsung
- MBA from 2010
- MBA from 2015
- MBP from 2008

But I don't get any excessive CPU usage of AnimatedGif when using those systems in different possible pairings. Not even when running MBA 15 and 4K Display in a 4K resolution I got problems.

So I wondering how to reproduce the problem? What could be special with your system?
Can you tell me some details about your configuration please?
-  your OSX Version 
  (I stay at 10.11.3 because higher version causes the known freezing problem on my MBA 2015.
- your Mac hardware in detail (GPU chip, etc. pp.)
- your Display hardware in detail
- connection you use between Display and Mac (Thunderbold, DisplayPort, HDMI, DVI, ...)
- the used GIF (as we see in older issue especially the GIF could be a reason, maybe you create your own 4K GIF (have no clue if this is even possible)?  )
- used resolution and refresh rate with problem
- the settings you set in AnimatedGif

Well hope we can catch the problem. Greetings

**Comment by shamesung** [comment]
I'm on the latest Sierra Beta 👍 
Tech Specs:
https://support.apple.com/kb/sp700?locale=en_US
Using thunderbolt to HDMI
Not 4K resolution (1080P)

edit: I'm an **idiot**, i'm using a quartz composition screensaver instead of yours

**Comment by Waitsnake** [comment]
Yea, I used them before too. One of the main reasons why I start to code my own screensaver was the high CPU usage of the quartz composition solution.
